//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.ValidarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidarService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidEmail", ReplyAction="*")]
        AplicacionWeb.ValidarService.IsValidEmailResponse IsValidEmail(AplicacionWeb.ValidarService.IsValidEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionWeb.ValidarService.IsValidEmailResponse> IsValidEmailAsync(AplicacionWeb.ValidarService.IsValidEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidEmail", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionWeb.ValidarService.IsValidEmailRequestBody Body;
        
        public IsValidEmailRequest() {
        }
        
        public IsValidEmailRequest(AplicacionWeb.ValidarService.IsValidEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsValidEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public IsValidEmailRequestBody() {
        }
        
        public IsValidEmailRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public AplicacionWeb.ValidarService.IsValidEmailResponseBody Body;
        
        public IsValidEmailResponse() {
        }
        
        public IsValidEmailResponse(AplicacionWeb.ValidarService.IsValidEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsValidEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsValidEmailResult;
        
        public IsValidEmailResponseBody() {
        }
        
        public IsValidEmailResponseBody(string IsValidEmailResult) {
            this.IsValidEmailResult = IsValidEmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : AplicacionWeb.ValidarService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<AplicacionWeb.ValidarService.WebServiceSoap>, AplicacionWeb.ValidarService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionWeb.ValidarService.IsValidEmailResponse AplicacionWeb.ValidarService.WebServiceSoap.IsValidEmail(AplicacionWeb.ValidarService.IsValidEmailRequest request) {
            return base.Channel.IsValidEmail(request);
        }
        
        public string IsValidEmail(string email) {
            AplicacionWeb.ValidarService.IsValidEmailRequest inValue = new AplicacionWeb.ValidarService.IsValidEmailRequest();
            inValue.Body = new AplicacionWeb.ValidarService.IsValidEmailRequestBody();
            inValue.Body.email = email;
            AplicacionWeb.ValidarService.IsValidEmailResponse retVal = ((AplicacionWeb.ValidarService.WebServiceSoap)(this)).IsValidEmail(inValue);
            return retVal.Body.IsValidEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionWeb.ValidarService.IsValidEmailResponse> AplicacionWeb.ValidarService.WebServiceSoap.IsValidEmailAsync(AplicacionWeb.ValidarService.IsValidEmailRequest request) {
            return base.Channel.IsValidEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionWeb.ValidarService.IsValidEmailResponse> IsValidEmailAsync(string email) {
            AplicacionWeb.ValidarService.IsValidEmailRequest inValue = new AplicacionWeb.ValidarService.IsValidEmailRequest();
            inValue.Body = new AplicacionWeb.ValidarService.IsValidEmailRequestBody();
            inValue.Body.email = email;
            return ((AplicacionWeb.ValidarService.WebServiceSoap)(this)).IsValidEmailAsync(inValue);
        }
    }
}
